jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: admin
      port: 5432
      dbname: jaffle_shop
      schema: dbt_alice
      threads: 4